//Data initialization
const product = [
    {productId: 1, category: "laptop", type: "laptop", brand: "ASUS", name: "ASUS E1404GA-NK350WSM/ CORE I3-N305", price: 27995.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/bfdfdbfbd_531a8ed8-8a32-4c50-a52d-78d987105986_800x.jpg?v=1733105085", desc:"The ASUS E1404GA-NK350WSM is a sleek and efficient laptop designed for everyday productivity and on-the-go use. Powered by an Intel Core i3-N305 processor, this device delivers reliable performance for essential tasks such as web browsing, document editing, and multimedia consumption. With 8GB of RAM, it ensures smooth multitasking, allowing users to switch between applications seamlessly, while the 256GB SSD provides fast boot times and ample storage for essential files and software.", desc1:"Built with portability in mind, this laptop features a lightweight and compact chassis, making it ideal for students and professionals who need a reliable companion for work or study. The long-lasting battery life ensures uninterrupted productivity throughout the day, whether in class, at the office, or while traveling. Additionally, the pre-installed Windows 11 operating system offers a modern, secure, and user-friendly experience, complete with essential productivity tools and seamless software compatibility.", desc2:"Designed for simplicity and convenience, the ASUS E1404GA-NK350WSM strikes a balance between performance and affordability. Its minimalist design, efficient hardware, and dependable battery make it a practical choice for everyday computing needs. Whether for note-taking, online learning, or casual entertainment, this laptop provides a hassle-free experience without unnecessary complexity.", feature:"Intel Core i3-N305 Processor: 8-core, 8-thread efficiency for smooth everyday computing, web browsing, and light multitasking.", feature1:"8GB DDR4 RAM + 256GB SSD: Ensures responsive performance for daily tasks and fast boot times with SSD storage.", feature2:"Lightweight Design: Ultra-portable 1.5kg chassis with a slim 17.9mm profile for easy mobility.", feature3:"All-Day Battery Life: Up to 10 hours of usage (ASUS claim) to power through work or classes.", feature4:"Windows 11 Pre-installed: Ready-to-use with the latest OS for security and productivity."},
    {productId: 2, category: "laptop", type: "laptop", brand: "TUF", name: "ASUS TUF FA507NUR-LP051W", price: 57995.00, image: "https://www.gigahertz.com.ph/cdn/shop/files/asus-tuf-fa507nur-lp051w-gaming-laptop-156-fhd-ryzen-7-7435hs-geforce-rtx-4050-16gb-ram-512gb-ssd-win-11-asus-gigahertz-571883_1024x.webp?v=1724036780", desc:"The ASUS TUF FA507NUR-LP051W is a high-performance gaming laptop built to deliver power and durability for gamers and creators alike. Equipped with an AMD Ryzen 7 7735HS processor and NVIDIA GeForce RTX 4050 GPU, it handles demanding games, 3D rendering, and multitasking with ease. The 16GB DDR5 RAM ensures smooth performance, while the 512GB PCIe SSD offers fast load times and ample storage for games and applications.", desc1:"Designed for resilience, this laptop features the TUF series' military-grade durability, ensuring it can withstand rigorous use. The 15.6-inch FHD 144Hz display provides crisp visuals and fluid gameplay, with Adaptive-Sync minimizing screen tearing for a competitive edge. Advanced cooling, including dual fans and anti-dust technology, keeps temperatures in check during extended gaming sessions, while the RGB-backlit keyboard enhances immersion and usability in low-light environments.", desc2:"Balancing power and portability, the ASUS TUF FA507NUR-LP051W is ideal for gamers and professionals seeking a reliable, high-performance machine. With Wi-Fi 6, Windows 11 pre-installed, and a robust selection of ports (including USB-C and HDMI 2.1), it's ready for both gaming and productivity. Whether battling in esports or tackling creative projects, this laptop delivers endurance, speed, and immersive visuals in a rugged yet sleek package.", feature:"AMD Ryzen 7 7735HS Processor: 8-core, 16-thread powerhouse for gaming and creative workloads.", feature1:"NVIDIA GeForce RTX 4050 GPU: 6GB GDDR6 with DLSS 3 and ray tracing for realistic visuals.", feature2:"Military-Grade Durability: Meets MIL-STD-810H standards for shock, vibration, and temperature resistance.", feature3:"144Hz Adaptive-Sync Display: Minimizes screen tearing for competitive gaming advantage.", feature4:"RGB Backlit Keyboard: Customizable per-key lighting with 1.7mm key travel for precise control."},
    {productId: 3, category: "laptop", type: "laptop", brand: "ACER", name: "ACER ASPIRE LITE AL14-31P-C582", price: 20999.00, image: "https://www.greentelcom.ph/wp-content/uploads/2025/01/ACER-ASPIRE-LITE-AL14-31P-C582-4.png", desc:"The Acer Aspire Lite AL14-31P-C582 is a sleek and lightweight laptop designed for everyday productivity and portability. Powered by an Intel Core i5-1235U processor, it delivers efficient performance for multitasking, office work, and multimedia consumption. With 16GB of RAM, users can smoothly run multiple applications, while the 512GB NVMe SSD ensures fast boot times and responsive file access. The 14-inch Full HD IPS display offers crisp visuals with wide viewing angles, making it ideal for work and entertainment.", desc1:"Built for on-the-go professionals and students, this laptop features a thin and durable aluminum chassis, weighing just under 1.5 kg for easy portability. The long-lasting battery life keeps you productive throughout the day, whether you're in meetings, classes, or working remotely. Additionally, it comes with Windows 11 pre-installed, providing a secure and user-friendly experience with seamless integration for productivity tools and software.", desc2:"Combining performance, style, and affordability, the Acer Aspire Lite AL14-31P-C582 is a practical choice for those seeking a reliable everyday laptop. Its backlit keyboard enhances usability in low-light environments, while the comprehensive connectivity options—including USB-C, HDMI, and Wi-Fi 6—ensure compatibility with modern peripherals and networks. Whether for work, study, or casual use, this laptop offers a balanced blend of functionality and elegance.", feature:"Intel Core i5-1235U Processor: 10-core (2P+8E) hybrid architecture for efficient multitasking.", feature1:"16GB LPDDR4X RAM: Ample memory for demanding applications and browser tabs.", feature2:"512GB NVMe SSD: Fast storage with quick boot times and application loading.", feature3:"14-inch FHD IPS Display: 300-nit brightness with anti-glare coating for outdoor use.", feature4:"Military-Grade Durability: Meets MIL-STD-810H standards for reliability."},
    {productId: 4, category: "laptop", type: "laptop", brand: "ACER", name: "ACER NITRO V ANV15-41-R2M0 OPI", price: 37999.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEaj-ABMcwGH6lqS1G0XgSUJl4PEPToeVmDg&s", desc:"The Acer Nitro V ANV15-41-R2M0 OPI is a powerful gaming laptop designed to deliver immersive performance for gamers and content creators. At its core lies the AMD Ryzen 5 7535HS processor and NVIDIA GeForce RTX 4050 GPU, providing the horsepower needed to handle modern AAA games, streaming, and creative workloads with ease. The 15.6-inch Full HD 144Hz display ensures smooth, tear-free visuals, while 16GB DDR5 RAM and a 512GB PCIe SSD offer lightning-fast load times and seamless multitasking.", desc1:"Engineered for endurance, this laptop features Acer's advanced cooling system, including dual fans and strategically placed vents, to maintain optimal temperatures during intense gaming sessions. The 4-zone RGB backlit keyboard not only enhances the gaming atmosphere but also improves visibility in low-light conditions. With Wi-Fi 6 connectivity and a robust selection of ports—including USB-C, HDMI 2.1, and multiple USB-A ports—the Nitro V ensures compatibility with peripherals and high-speed networks.", desc2:"Balancing performance and affordability, the Acer Nitro V ANV15-41-R2M0 OPI is an excellent choice for gamers seeking a reliable and feature-packed machine. Pre-installed with Windows 11, it offers a smooth and secure out-of-the-box experience. Whether you're diving into competitive esports or tackling demanding creative projects, this laptop delivers the speed, visuals, and durability needed to stay ahead in the game.", feature:"AMD Ryzen 5 7535HS Processor: 6-core, 12-thread Zen 3+ architecture for gaming performance.", feature1:"NVIDIA GeForce RTX 4050: 6GB GDDR6 with DLSS 3 and ray tracing support.", feature2:"NitroSense Cooling: Dual-fan system with CoolBoost technology for sustained performance.", feature3:"4-Zone RGB Keyboard: Customizable backlighting with highlighted WASD keys.", feature4:"Killer Ethernet E2600: Prioritizes gaming traffic for lag-free online play."},
    {productId: 5, category: "laptop", type: "laptop", brand: "LENOVO", name: "LENOVO IP S3I-15 (83ER00EMP)", price: 27995.00, image: "https://www.gigahertz.com.ph/cdn/shop/files/lenovo-ideapad-slim-3-15irh8-83em000eph-156-fhd-i5-13420h-uhd-graphics-16gb-ram-512gb-ssd-win-11-lenovo-gigahertz-944428_1024x.jpg?v=1726732496", desc: "The Lenovo IdeaPad Slim 3i 15 (83ER00EMP) combines productivity and portability with an Intel Core i5-13420H processor, 16GB RAM, and 512GB SSD. Its 15.6-inch FHD display and lightweight design make it ideal for work or study on the go.", desc1: "Featuring a sleek chassis, ergonomic keyboard, and privacy-focused webcam shutter, this laptop prioritizes security and comfort. With Wi-Fi 6, USB-C, HDMI, and Windows 11 pre-installed, it ensures seamless connectivity and modern performance.", desc2: "Perfect for professionals and students, the IdeaPad Slim 3i balances power and affordability. Its long battery life and minimalist design cater to everyday tasks, from office work to entertainment, all in a portable package.", feature:"Intel Core i5-13420H Processor: 10-core (4P+6E) hybrid architecture for responsive performance.", feature1:"16GB DDR4 RAM: Smooth multitasking for office applications and web browsing.", feature2:"Privacy Shutter: Physical cover for the 720p HD webcam for enhanced security.", feature3:"Rapid Charge: 0-80% in just 1 hour for quick power top-ups.", feature4:"Dolby Audio: Dual speakers with smart noise cancellation for clear calls."},
    {productId: 6, category: "laptop", type: "laptop", brand: "HP", name: "HP 14-EP0193TU/ CORE I3-N305/ 8GB DDR4/", price: 24990.00, image: "https://i5.walmartimages.com/seo/HP-14-inch-Laptop-Intel-Core-i3-N305-8GB-RAM-256GB-SSD-Moonlight-Blue_3c814651-0efa-4e3c-9598-efb385991581.8bd1455c08963f272709c63b7f0dbf40.jpeg", desc:"The HP 14-EP0193TU is a compact and efficient laptop powered by an Intel Core i3-N305 processor, delivering reliable performance for everyday computing tasks. With 8GB DDR4 RAM and 256GB SSD storage, it offers smooth multitasking and quick boot times.", desc1:"Featuring a 14-inch HD display in a sleek Moonlight Blue chassis, this lightweight laptop is perfect for students and professionals on the move. The long battery life ensures productivity throughout the day, while Windows 11 provides a modern and secure operating system.", desc2:"Ideal for web browsing, document editing, and multimedia consumption, this HP laptop combines affordability with essential features including USB-C connectivity, Wi-Fi 6, and a built-in webcam for video conferencing.", feature:"Intel Core i3-N305 Processor: 8-core efficiency core architecture for basic computing needs.", feature1:"8GB DDR4 RAM: Adequate memory for everyday office and student workloads.", feature2:"256GB NVMe SSD: Faster storage than traditional HDDs with quick boot times.", feature3:"HP Fast Charge: 50% charge in 45 minutes for quick power boosts.", feature4:"HP Audio Boost: Dual speakers tuned by audio experts for clear sound."},
    {productId: 7, category: "laptop", type: "laptop", brand: "HP", name: "HP 15S-EQ2323AU/ RYZEN 3-5300U", price: 23990.00, image: "https://store.gigatechph.com/cdn/shop/files/HPIA46S6PA_front_2048x.jpg?v=1716271030", desc:"The HP 15S-EQ2323AU features an AMD Ryzen 3-5300U processor that balances performance and power efficiency for everyday computing. The 15.6-inch Full HD display offers vibrant visuals in a slim and portable design, making it ideal for both work and entertainment. With its energy-efficient architecture, this laptop delivers responsive performance while maintaining excellent battery life, perfect for students and mobile professionals.", desc1:"Equipped with 8GB RAM and 256GB SSD, this laptop handles multitasking with ease while providing ample storage space for documents and media. The ergonomic keyboard with numeric pad enhances productivity for data entry tasks, and the fast-charging battery keeps you powered throughout the day. The anti-glare display reduces eye strain during extended use, while the HD webcam with integrated microphone ensures clear video calls for remote work or online classes.", desc2:"Perfect for home and office use, it comes with Windows 11 pre-installed and features modern connectivity options including USB-C, HDMI, and Wi-Fi 5. The minimalist silver design complements any workspace environment, while the dual speakers deliver surprisingly rich audio for its class. HP's built-in security features like BIOS protection and secure boot provide peace of mind for sensitive work, making this a well-rounded choice for budget-conscious buyers.", feature:"AMD Ryzen 3 5300U Processor: 4-core, 8-thread Zen 2 architecture with Radeon Graphics.", feature1:"15.6-inch FHD Anti-Glare Display: 250-nit brightness for comfortable viewing indoors.", feature2:"Fast Charge Technology: 50% charge in just 45 minutes for quick power top-ups.", feature3:"HP Audio Boost: Dual speakers with software enhancement for clearer sound.", feature4:"Windows 11 Home: Pre-installed with latest security features and productivity tools."},
    {productId: 8, category: "laptop", type: "laptop", brand: "HUAWEI", name: "HUAWEI MATEBOOK D15/ CORE I3-10110U", price: 28999.00, image: "https://www.octagon.com.ph/cdn/shop/products/1_76ee11ce-8b49-48a2-b49b-51c06ac364ae.jpg?v=1652404094", desc:"The Huawei MateBook D15 combines elegant design with capable performance, featuring an Intel Core i3-10110U processor and 8GB RAM. The 15.6-inch FullView display offers an immersive viewing experience with thin bezels and 1080p resolution, achieving an impressive 87% screen-to-body ratio. This ultrabook exemplifies Huawei's commitment to minimalist design without compromising functionality, making it ideal for professionals who value aesthetics as much as performance.", desc1:"Built with premium aluminum alloy, this ultrabook is both durable and lightweight at just 1.53kg, featuring a sleek space-gray finish that resists fingerprints. The fingerprint power button provides instant secure login through Windows Hello, while the hidden pop-up webcam ensures privacy when not in use – a clever solution that eliminates the need for a privacy shutter. The full-size backlit keyboard offers comfortable typing even in low-light conditions, and the large precision touchpad supports multi-touch gestures for intuitive control.", desc2:"With 256GB SSD storage, dual-band Wi-Fi, and Huawei Share for seamless device connectivity, the MateBook D15 bridges the gap between smartphone and laptop productivity. The innovative multi-screen collaboration feature allows you to mirror your Huawei phone on the laptop display for easy file transfers and app control. The 56Wh battery provides all-day endurance, while the 65W USB-C fast charger can also power compatible Huawei phones. This ecosystem approach makes the MateBook D15 particularly valuable for existing Huawei smartphone users.", feature:"Intel Core i3-10110U Processor: 2-core, 4-thread 10th Gen CPU with Intel UHD Graphics.", feature1:"FullView Display: 15.6-inch FHD IPS with 87% screen-to-body ratio and 178° viewing angles.", feature2:"Huawei Share: One-touch file transfer between Huawei phones and laptop.", feature3:"Fingerprint Power Button: Integrated sensor for secure one-touch login.", feature4:"Pop-Up Webcam: 720p HD camera that retracts into keyboard for privacy."},
    {productId: 9, category: "laptop", type: "laptop", brand: "ACER", name: "ACER ASPIRE 5 A514-54G-51PU/ CORE I5", price: 24999.00, image: "https://i.pinimg.com/736x/90/4e/28/904e28f4d50b2532c200731a3aa5b02c.jpg", desc:"The Acer Aspire 5 A514-54G delivers powerful performance with its 11th Gen Intel Core i5 processor and NVIDIA MX350 graphics, making it an excellent choice for both work and light creative tasks. The 14-inch Full HD IPS display features narrow bezels for an immersive viewing experience, while the aluminum top cover adds durability without compromising portability at just 1.45kg. With 8GB DDR4 RAM and 512GB NVMe SSD, this laptop handles everyday productivity with ease, from office applications to photo editing.", desc1:"Designed for professionals who value both performance and aesthetics, the Aspire 5 features a backlit keyboard with 1.6mm key travel for comfortable typing, along with a fingerprint reader for secure Windows Hello login. The comprehensive connectivity options include USB 3.2 Gen 1 ports, USB-C, HDMI 2.0, and Wi-Fi 6, ensuring compatibility with modern peripherals. Acer's Color Intelligence technology dynamically optimizes screen gamma and saturation for vibrant visuals, while BlueLightShield reduces eye strain during extended use.", desc2:"This versatile laptop strikes the perfect balance between productivity and entertainment, offering up to 10 hours of battery life for all-day use. The dual-band Wi-Fi maintains stable connections in busy environments, while the HD webcam with temporal noise reduction ensures clear video calls. Whether you're crunching numbers, streaming content, or working remotely, the Aspire 5 delivers reliable performance in a sleek, professional package.", feature:"11th Gen Intel Core i5-1135G7: 4-core, 8-thread processor with Iris Xe graphics.", feature1:"NVIDIA MX350 GPU: 2GB GDDR5 for light creative work and casual gaming.", feature2:"Military-Grade Durability: Meets MIL-STD-810G standards for reliability.", feature3:"Acer Color Intelligence: Dynamically adjusts display color gamut for optimal visuals.", feature4:"Wi-Fi 6 (802.11ax): Faster wireless speeds with improved efficiency."},
    {productId: 10, category: "laptop", type: "laptop", brand: "LENOVO", name: "LENOVO IPS3-14 (81X7004UPH) CORE I3", price: 29995.00, image: "https://www.makotekcomputers.com/cdn/shop/files/LENOVO-IDEAPAD-SLIM-3-14IGL05-81WH002TPH-BLACK-14-HD-ANTI-GLARE-DISPLAY-INTEL-PENTIUM-SILVER-N5030-4GB-DDR4-512GB-M_2-NVME-PCIE-3_0-x4-SSD-INTEL-UHD-GRAPHICS-W10-12-MONTHS-WARRANTY-5.jpg?v=1739923144&width=1946", desc:"The Lenovo IdeaPad Slim 3 14 features an Intel Core i3 processor in a lightweight 14-inch chassis, offering essential productivity in a highly portable form factor. The anti-glare HD display reduces eye strain during extended use, while the 512GB NVMe SSD provides quick boot times and responsive application loading. Weighing just 1.6kg with a slim profile, this laptop is ideal for students and mobile professionals who prioritize portability.", desc1:"Practical features include a physical webcam shutter for privacy, Dolby Audio speakers for clear sound, and a comfortable keyboard with spill resistance. The 4GB RAM (expandable up to 12GB) handles basic multitasking, while the Intel UHD Graphics supports casual media consumption. With up to 7 hours of battery life, Windows 11 pre-installed, and a minimalist design, this laptop covers all the essentials without unnecessary frills.", desc2:"Connectivity includes USB 3.2 Gen 1, USB-C, HDMI, and Wi-Fi 5 for versatile peripheral support. The durable plastic chassis withstands daily commuting, while the rapid charge capability provides quick power boosts when needed. For those seeking an affordable, no-nonsense laptop for web browsing, document editing, and video calls, the IdeaPad Slim 3 delivers reliable performance in a compact package.", feature:"Intel Core i3-1115G4: Dual-core, 4-thread 11th Gen processor with UHD Graphics.", feature1:"Expandable Memory: 4GB DDR4 (1x slot free) upgradable to 12GB total.", feature2:"Privacy Protection: Physical webcam shutter and firmware-level security.", feature3:"Dolby Audio: Dual 1.5W speakers with smart amplifier.", feature4:"Rapid Charge: 80% charge in just 1 hour for quick power top-ups."},
    {productId: 11, category: "laptop", type: "laptop", brand: "APPLE", name: "MacBook Air 13-inch", price: 64990.00, image: "https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/macbook-air-13-digitalmat-gallery-1-202503?wid=728&hei=666&fmt=png-alpha&.v=1739590110917", desc:"The MacBook Air 13-inch with M1 chip redefines ultraportable computing with breakthrough performance and up to 18 hours of battery life - the longest ever in a MacBook Air. The Retina display offers stunning 2560x1600 resolution with True Tone technology that automatically adjusts color temperature to match ambient lighting. The fanless design remains completely silent even under load, while the aluminum unibody construction maintains Apple's signature premium feel at just 1.29kg.", desc1:"Featuring Apple's revolutionary M1 chip with 8-core CPU, 7-core GPU, and 16-core Neural Engine, this MacBook delivers performance that rivals many pro laptops. The Magic Keyboard provides comfortable typing with 1mm key travel, while Touch ID enables secure authentication and Apple Pay. With 8GB unified memory and 256GB SSD storage, the MacBook Air handles everything from professional creative work to intensive multitasking with remarkable efficiency.", desc2:"The macOS ecosystem offers seamless integration with iPhone and iPad, including features like Handoff, Universal Clipboard, and Sidecar. Two Thunderbolt/USB 4 ports support high-speed peripherals and external displays up to 6K resolution. Whether you're a student, creative professional, or business user, the M1 MacBook Air combines unparalleled portability with desktop-class performance in a beautifully designed package.", feature:"Apple M1 Chip: 8-core CPU + 7-core GPU + 16-core Neural Engine for breakthrough performance.", feature1:"18-Hour Battery Life: Longest battery ever in a MacBook Air for all-day use.", feature2:"Retina Display: 2560x1600 resolution with P3 wide color and True Tone.", feature3:"Fanless Design: Silent operation with no moving parts.", feature4:"macOS Ecosystem: Seamless integration with iPhone/iPad and exclusive apps."},
    {productId: 12, category: "laptop", type: "laptop", brand: "ACER", name: "ACER NITRO 5 AN515-55-50S0/ CORE I5", price: 52999.00, image: "https://i5.walmartimages.com/asr/56fc310e-c641-4268-9876-3688ce1c2d8f.7e3ac37b5f3bf57f3eff28fa4556cf61.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF", desc:"The Acer Nitro 5 gaming laptop packs serious power with its 10th Gen Intel Core i5 processor and NVIDIA GeForce GTX 1650 Ti graphics, delivering smooth gameplay at 1080p for popular esports titles. The 15.6-inch Full HD 144Hz IPS display ensures fast response times with 3ms overdrive, while the dual-fan cooling system with Acer CoolBoost technology keeps temperatures in check during marathon gaming sessions. With 8GB DDR4 RAM (expandable to 32GB) and 512GB NVMe SSD, this machine handles modern games and multitasking with ease.", desc1:"Designed for gamers who demand performance at an accessible price point, the Nitro 5 features a red-backlit keyboard with highlighted WASD keys, NitroSense control panel for real-time performance monitoring, and comprehensive connectivity including HDMI 2.0, USB 3.2 Gen 2, and Killer Ethernet for lag-free online play. The aggressive angular chassis houses a user-upgradeable design, allowing easy access to RAM and storage slots for future expansions. The DTS:X Ultra audio enhances immersion with virtual 7.1-channel surround sound through headphones.", desc2:"Balancing power and practicality, this laptop includes a 56Wh battery for moderate mobile use and a 180W power adapter for full performance. The textured palm rest resists fingerprints during intense gameplay, while the narrow bezels maximize screen real estate. Whether you're battling in competitive shooters or exploring open-world RPGs, the Nitro 5 delivers reliable frame rates and thermal performance in a package that won't break the bank.", feature:"NVIDIA GTX 1650 Ti: 4GB GDDR6 GPU with Turing architecture for 1080p gaming.", feature1:"144Hz IPS Display: 3ms response time with 72% NTSC color gamut.", feature2:"CoolBoost Technology: Dual fans with adjustable speed via NitroSense.", feature3:"Killer Ethernet E2600: Prioritizes gaming traffic for lower ping.", feature4:"DTS:X Ultra Audio: Virtual surround sound for headphones."},
    {productId: 13, category: "laptop", type: "laptop", brand: "APPLE", name: "MacBook Pro 14-inch", price: 99990.00, image: "https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/mbp-14-digitalmat-gallery-1-202410?wid=728&hei=666&fmt=png-alpha&.v=1728342371746", desc:"The MacBook Pro 14-inch with M2 Pro chip represents the pinnacle of professional laptop performance, featuring a stunning Liquid Retina XDR display with ProMotion technology up to 120Hz refresh rate. The mini-LED backlight delivers 1000 nits sustained brightness (1600 nits peak) with perfect blacks and a 1,000,000:1 contrast ratio, making it ideal for color-critical work in photography, video editing, and graphic design. The 16-core Neural Engine accelerates machine learning tasks, while up to 32GB unified memory ensures smooth handling of intensive creative workflows.", desc1:"Built for power users, this laptop features an advanced thermal system with 30% more airflow than previous models, enabling sustained performance without throttling. The 1080p FaceTime HD camera with computational video and the six-speaker sound system with force-cancelling woofers redefine virtual meetings and media consumption. Professional-grade connectivity includes three Thunderbolt 4 ports, HDMI 2.1, SDXC slot, and MagSafe 3 charging with fast charge capability (50% in 30 minutes).", desc2:"The redesigned chassis combines durability with elegance, featuring a 16.2mm thin unibody aluminum construction at just 1.6kg. The Magic Keyboard now includes a full-height function row and a physical Escape key, while the Touch ID sensor enables secure authentication. For developers, video editors, and creative professionals who demand the best, the 14-inch MacBook Pro delivers desktop-class performance in a portable form factor with industry-leading battery life (up to 17 hours video playback).", feature:"M2 Pro Chip: 10/12-core CPU + 16/19-core GPU + 16-core Neural Engine.", feature1:"Liquid Retina XDR: 3024x1964 mini-LED display with 120Hz ProMotion.", feature2:"ProRes Acceleration: Hardware-accelerated encode/decode for video workflows.", feature3:"Six-Speaker Sound: Spatial audio with force-cancelling woofers.", feature4:"96W USB-C Power Adapter: Includes fast charge capability."},
    {productId: 14, category: "laptop", type: "laptop", brand: "HUAWEI", name: "HUAWEI MATEBOOK D15 (2020)/ RYZEN 5", price: 35999.00, image: "https://technave.com/data/files/mall/article/202009070728539323.jpg", desc:"The Huawei MateBook D15 (2020) features AMD Ryzen 5 3500U processor with Radeon Vega 8 graphics, delivering balanced performance for both productivity and light creative work. The 15.6-inch FullView display offers an impressive 87% screen-to-body ratio with thin 5.3mm bezels, while the ultra-slim 16.9mm aluminum body weighs just 1.53kg for exceptional portability. With 8GB DDR4 RAM and 512GB SSD, this laptop provides responsive performance for office applications, multimedia editing, and casual gaming.", desc1:"Huawei's innovative features shine with the fingerprint power button that enables one-touch login, and Huawei Share which allows seamless file transfer between Huawei phones and laptop by simply tapping your device on the NFC area. The full-size backlit keyboard offers 1.5mm key travel for comfortable typing, while the hidden pop-up webcam preserves privacy when not in use. The dual-band Wi-Fi 5 and comprehensive port selection (including USB-C and HDMI) ensure compatibility with modern peripherals.", desc2:"Designed for mobile professionals, the MateBook D15 delivers up to 10 hours of battery life with 65W fast charging (0-53% in 30 minutes). The dual speakers with Huawei Histen audio enhancement provide clear sound for video calls and entertainment. The minimalist space gray finish resists fingerprints, while the 178° wide-viewing-angle IPS panel makes it ideal for collaborative work. For users invested in the Huawei ecosystem, this laptop offers exceptional value with premium build quality and smart features.", feature:"AMD Ryzen 5 3500U: 4-core, 8-thread processor with Radeon Vega 8 Graphics.", feature1:"Huawei Share: NFC-based multi-screen collaboration with Huawei phones.", feature2:"FullView Display: 87% screen-to-body ratio with 178° viewing angles.", feature3:"Pop-Up Webcam: 720p HD camera hidden in keyboard for privacy.", feature4:"65W Fast Charge: USB-C charger compatible with Huawei phones."},
    {productId: 15, category: "laptop", type: "laptop", brand: "ACER", name: "ACER ASPIRE 5 A515-55G-55S8", price: 31999.00, image: "https://images.acer.com/is/image/acer/aspire5-a51555-bl-fp-wp-bk-1-bl-1", desc:"The Acer Aspire 5 A515-55G-55S8 combines productivity and entertainment with its 10th Gen Intel Core i5 processor and NVIDIA GeForce MX350 graphics, making it ideal for both office work and light creative tasks. The 15.6-inch Full HD IPS display features Acer Color Intelligence for vibrant visuals, while the aluminum top cover adds durability without adding weight (1.8kg). With 8GB DDR4 RAM and 512GB NVMe SSD, this laptop handles multitasking smoothly, from spreadsheet work to photo editing.", desc1:"Practical features include an ergonomic keyboard with numeric pad for data entry, fingerprint reader for secure login, and comprehensive connectivity including USB 3.2 Gen 1, USB-C, and HDMI 2.0. The dual-band Wi-Fi 6 ensures stable connections in busy environments, while the HD webcam with temporal noise reduction delivers clear video calls. Acer's BlueLightShield technology reduces eye strain during extended use, making this laptop comfortable for all-day productivity.", desc2:"Designed for value-conscious users who need balanced performance, the Aspire 5 offers up to 8 hours of battery life for mobile use. The dual speakers with Acer TrueHarmony provide surprisingly rich audio for its class, while the MIL-STD-810G compliant construction ensures reliability. Whether you're working remotely, studying, or enjoying multimedia content, this laptop delivers dependable performance in a professional package.", feature:"10th Gen Intel Core i5-1035G1: 4-core, 8-thread processor with 3.6GHz boost.", feature1:"NVIDIA MX350 GPU: 2GB GDDR5 for light creative work and casual gaming.", feature2:"Wi-Fi 6 (802.11ax): Faster speeds and better efficiency in crowded networks.", feature3:"Fingerprint Reader: Windows Hello compatible one-touch login.", feature4:"Military-Grade Durability: Meets MIL-STD-810G standards for reliability."},
    {productId: 16, category: "peripheral", type: "keyboard", brand: "RAZER", name: "RAZER BLACKWIDOW V3 MINI GREEN SWITCH KEYBOARD", price: 5995.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwKrG6GzRAc6pvv_eCTj7zBPEtgoHJyH2bEQ&s", desc:"The Razer BlackWidow V3 Mini HyperSpeed redefines compact gaming keyboards with its 65% form factor that saves desk space without sacrificing functionality. Featuring Razer Green Mechanical Switches, this keyboard delivers tactile and clicky feedback preferred by typists and gamers alike, with actuation force of 50g and durability rated for 80 million keystrokes. The doubleshot ABS keycaps ensure long-lasting durability against wear and fading, while the multi-device Bluetooth and HyperSpeed wireless technology offer versatile connectivity options.", desc1:"Designed for competitive gamers and minimalists, the BlackWidow V3 Mini features onboard memory for up to 5 profile storages, allowing you to take your custom configurations anywhere. The customizable Chroma RGB backlighting with 16.8 million colors creates immersive lighting effects that sync across Razer peripherals. The aluminum construction provides stability during intense gaming sessions, while the detachable USB-C cable enhances portability. The 65% layout eliminates the numpad and function row for a cleaner setup, focusing on essential keys for gaming.", desc2:"This keyboard isn't just about aesthetics - it delivers tournament-ready performance with full N-key rollover and anti-ghosting technology. The included keyboard case protects your investment during travel, while the ergonomic feet offer adjustable typing angles. Whether you're a esports competitor needing reliable wireless performance or a streamer looking to declutter your setup, the BlackWidow V3 Mini combines Razer's signature quality in a space-saving design.", feature:"Razer Green Switches: Tactile and clicky with 50g actuation force.", feature1:"HyperSpeed Wireless: Industry-leading 2.4GHz connection with multi-device pairing.", feature2:"Chroma RGB: 16.8 million colors with per-key customization.", feature3:"Doubleshot ABS Keycaps: Wear-resistant legends that won't fade.", feature4:"Compact 65% Layout: Saves 30% more space than full-size keyboards."},
    {productId: 17, category: "peripheral", type: "keyboard", brand: "LOGITECH", name: "LOGITECH MX KEYS S PALE GRAY KEYBOARD", price: 6995.00, image: "https://storage.googleapis.com/bionic_1626848719/products/3aebae77ae3c02f40c876ab5d1f1e1ced1f135a9/banners/12900592_1701696785.jpg", desc:"The Logitech MX Keys S elevates wireless typing to an art form with its Perfect Stroke keys and smart backlighting that activates when hands approach. This premium keyboard features a low-profile scissor mechanism that provides quiet, precise typing with just 2.4mm key travel, making it ideal for writers, coders, and professionals who spend hours at their desks. The pale gray minimalist design with matte finish complements modern workspaces while resisting fingerprints and smudges.", desc1:"With multi-device Bluetooth connectivity and Logi Bolt USB receiver, you can pair with up to 3 devices and switch between them instantly - perfect for multi-computer setups. The smart illumination adjusts to lighting conditions and turns off when not in use to conserve battery, providing up to 10 days of use on a full charge (or 5 months with backlighting off). The integrated USB-C charging allows you to power up quickly, getting 3 hours of use from just 1 minute of charging.", desc2:"Designed for creators and power users, the MX Keys S includes customizable function keys that can launch apps, switch desktops, or control smart home devices. The concave keycaps cradle your fingertips for natural typing, while the sturdy metal construction ensures stability. Whether you're working from home or in a busy office, this keyboard delivers exceptional comfort and versatility with Logitech's signature reliability.", feature:"Perfect Stroke Keys: Spherically-dished keys for accurate fingertip alignment.", feature1:"Smart Illumination: Auto-adjusts brightness and turns off when idle.", feature2:"Multi-Device Pairing: Connect to 3 devices via Bluetooth/Logi Bolt.", feature3:"USB-C Quick Charge: 3 hours use from 1-minute charge.", feature4:"Customizable F-Keys: Programmable for apps, macros, or smart controls."},
    {productId: 18, category: "peripheral", type: "keyboard", brand: "LOGITECH", name: "LOGITECH G413 TKL KEYBOARD MECHANICAL", price: 4145.00, image: "https://d1rlzxa98cyc61.cloudfront.net/catalog/product/1/8/181909_2023_1.jpg?auto=webp&format=pjpg&width=640", desc:"The Logitech G413 TKL is a tenkeyless mechanical gaming keyboard featuring exclusive Romer-G mechanical switches with 45g actuation force for rapid, precise inputs. The aircraft-grade 5052 aluminum alloy top case provides durability while keeping the weight light at just 865g, making it ideal for gamers who need a portable yet sturdy keyboard.", desc1:"With a minimalist design and white LED backlighting, this keyboard offers understated style that fits any setup. The USB passthrough port provides convenient connectivity for mice or headsets, while the 12-key rollover ensures accurate input recognition during intense gaming sessions.", desc2:"Perfect for gamers who prefer a compact form factor without sacrificing performance, the G413 TKL delivers professional-grade features at an accessible price point. The textured keycaps provide enhanced grip, and the detachable micro-USB cable makes transportation easy.", feature:"Romer-G Switches: Tactile mechanical switches with 45g actuation force", feature1:"Aircraft-Grade Aluminum: Durable 5052 alloy construction", feature2:"USB Passthrough: Additional port for peripherals", feature3:"White LED Backlighting: Adjustable brightness", feature4:"Tenkeyless Design: Compact form factor saves space"},
    {productId: 19, category: "peripheral", type: "mouse", brand: "A4", name: "A4 TECH OP-330 BLACK WIRED MOUSE", price: 250.00, image: "https://www.complink.com.ph/cdn/shop/products/000003_28160_500x500.jpg?v=1641883307", desc:"The A4 Tech OP-330 is an essential wired optical mouse that delivers reliable performance for everyday computing tasks. With 1000DPI resolution, this no-frills mouse provides accurate tracking on most surfaces.", desc1:"Featuring a standard three-button configuration with scroll wheel, the OP-330 covers all basic computing needs. The durable rubber scroll wheel ensures smooth navigation, while the 1.5m braided cable adds longevity.", desc2:"Ideal for office or home use where simple functionality is prioritized, this mouse represents excellent value. The symmetrical design comfortably accommodates both right and left-handed users.", feature:"1000DPI Optical Sensor", feature1:"Ambidextrous Design", feature2:"Braided Cable", feature3:"Three-Button Layout", feature4:"Plug-and-Play Operation"},
    {productId: 20, category: "peripheral", type: "mouse", brand: "RAZER", name: "RAZER DEATHADDER V3 USB ERGONOMIC", price: 2995.00, image: "https://assets3.razerzone.com/fgOxqPbg2c_3ZaR4lajdYcIdhRs=/300x300/https%3A%2F%2Fmedias-p1.phoenix.razer.com%2Fsys-master-phoenix-images-container%2Fh79%2Fhaf%2F9529652674590%2Fdeathadder-v3-2-500x500.png", desc:"The Razer DeathAdder V3 continues the legendary ergonomic design with improved form factor and 59% lighter weight than previous versions. The Focus Pro 30K optical sensor delivers flawless tracking performance.", desc1:"Engineered for competitive play, this mouse features eight programmable buttons that can be customized through Razer Synapse software. The PTFE mouse feet glide smoothly across any surface.", desc2:"This esports-grade mouse represents the pinnacle of FPS gaming peripherals, trusted by professionals worldwide. The optimized weight distribution provides perfect balance for precise aiming.", feature:"Focus Pro 30K Sensor", feature1:"Gen-3 Optical Switches", feature2:"Ultra-Lightweight 63g Design", feature3:"Speedflex Cable", feature4:"8 Programmable Buttons"},
    {productId: 21, category: "peripheral", type: "mouse", brand: "LOGITECH", name: "Logitech Wireless Mouse B175", price: 475.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-cjo1_hC-W-vOX3xSWUs4qjaF2kVtQ3cxEA&s", desc:"The Logitech Wireless Mouse B175 offers reliable wireless connectivity via nano receiver with a range up to 10m. The contoured shape provides comfortable grip for extended use.", desc1:"With 12-month battery life from a single AA battery and 1000DPI optical tracking, this mouse delivers dependable performance. The plug-and-play setup requires no software installation.", desc2:"Ideal for office or home use, the compact size makes it easy to carry while traveling. The scroll wheel and three-button configuration provide essential functionality.", feature:"1000DPI Optical Sensor", feature1:"12-Month Battery Life", feature2:"10m Wireless Range", feature3:"Plug-and-Play Setup", feature4:"Compact Portable Design"},
    {productId: 22, category: "peripheral", type: "speaker", brand: "JBL", name: "JBL GO 4 BT BLACK SPEAKER PORTABLE WATER", price: 2599.00, image: "https://onward.ph/cdn/shop/files/JBLGo4_Main_Black.png?v=1741527765", desc:"The JBL GO 4 is a compact Bluetooth speaker with IP67 waterproof and dustproof rating, making it perfect for outdoor adventures. The redesigned fabric material and rubber housing provide durability.", desc1:"Featuring JBL Pro Sound technology, this portable speaker delivers surprisingly powerful audio from its 40mm driver. The 5-hour playtime ensures entertainment throughout the day.", desc2:"With Bluetooth 5.3 connectivity and speakerphone functionality, you can enjoy wireless music streaming and clear hands-free calls. The built-in strap adds convenience.", feature:"IP67 Waterproof & Dustproof", feature1:"JBL Pro Sound Technology", feature2:"5-Hour Playtime", feature3:"Bluetooth 5.3", feature4:"Built-in Strap"},
    {productId: 23, category: "peripheral", type: "speaker", brand: "RAZER", name: "RAZER LEVIATHAN V2 X BLACK PC GAMING SPEAKER", price: 4995.00, image: "https://i.ebayimg.com/images/g/JX8AAOSw06tj9U7H/s-l1200.jpg", desc:"The Razer Leviathan V2 X is a compact soundbar designed specifically for gaming setups, featuring custom-tuned full-range drivers that deliver clear mids and highs.", desc1:"With Bluetooth 5.2 and 3.5mm auxiliary input, this speaker offers versatile connectivity options. The dedicated gaming mode optimizes sound for immersive gameplay.", desc2:"The sleek black design with Razer Chroma RGB lighting adds stylish ambiance to any desktop. At just 70cm wide, it fits perfectly beneath most monitors.", feature:"Custom-Tuned Full-Range Drivers", feature1:"Bluetooth 5.2 Connectivity", feature2:"Dedicated Gaming Mode", feature3:"Razer Chroma RGB", feature4:"Compact 70cm Design"},
    {productId: 24, category: "peripheral", type: "speaker", brand: "JBL", name: "JBL GO 3 BT BLUE SPEAKER PORTABLE", price: 2399.00, image: "https://jblstore.com.ph/cdn/shop/files/Go_3_Blue_Pink_Android_AR_Asset_NOBG_2000x.png?v=1741527555", desc:"The JBL GO 3 in vibrant blue features IP67 waterproof and dustproof rating, making it ideal for outdoor activities. The ultra-compact design fits in the palm of your hand.", desc1:"With 5 hours of playtime on a single charge, this portable Bluetooth speaker keeps the music going. The integrated loop makes it easy to carry or attach to backpacks.", desc2:"Simple controls allow easy playback management, and the Bluetooth 5.1 connectivity ensures stable wireless streaming from smartphones, tablets, or laptops.", feature:"IP67 Water & Dust Proof", feature1:"5-Hour Playtime", feature2:"Integrated Carry Loop", feature3:"Bluetooth 5.1", feature4:"Ultra-Compact Design"},
    {productId: 25, category: "peripheral", type: "microphone", brand: "RAZER", name: "RAZER SEIREN V3 MINI ULTRA-COMPACT USB", price: 2995.00, image: "https://gameone.ph/media/catalog/product/cache/d378a0f20f83637cdb1392af8dc032a2/r/a/razer-seirin-v3.jpg", desc:"The Razer Seiren V3 Mini is a professional-grade USB condenser microphone in an ultra-compact form factor. The 14mm condenser capsule captures clear, detailed vocals perfect for streaming.", desc1:"Featuring a built-in shock mount to reduce vibrations and a supercardioid pickup pattern that focuses on your voice while minimizing background noise.", desc2:"With plug-and-play USB connectivity and real-time monitoring via 3.5mm headphone jack, this microphone offers studio-quality recording without complicated setup.", feature:"14mm Condenser Capsule", feature1:"Supercardioid Pickup Pattern", feature2:"Built-in Shock Mount", feature3:"Plug-and-Play USB", feature4:"Real-Time Monitoring"},
    {productId: 26, category: "peripheral", type: "microphone", brand: "TITAN", name: "TITAN TCM-005U USB MICROPHONE LIGHTED", price: 795.00, image: "https://www.octagon.com.ph/cdn/shop/products/1_067675a3-7642-40b8-952a-6cbac402c012.jpg?v=1652690907", desc:"The Titan TCM-005U USB microphone features built-in RGB lighting that adds vibrant ambiance to your streaming setup. The cardioid pickup pattern focuses on sound from the front.", desc1:"With plug-and-play USB connectivity, this microphone is ready to use without drivers. The adjustable stand allows flexible positioning.", desc2:"Ideal for podcasting or gaming commentary, this budget-friendly mic delivers clear audio quality with 16-bit/48kHz sampling rate.", feature:"Built-in RGB Lighting", feature1:"Cardioid Pickup Pattern", feature2:"Plug-and-Play USB", feature3:"Adjustable Stand", feature4:"16-bit/48kHz Sampling"},
    {productId: 27, category: "peripheral", type: "microphone", brand: "SCORPION", name: "SCORPION MIC-05 BLACK GAMING RGB USB MIC", price: 795.00, image: "https://igabiba.com/cdn/shop/files/marvo-mic-05-wired-microphone-rgb-6932391923450-53143916052826_800x.png?v=1709045941", desc:"The Scorpion MIC-05 gaming microphone features dynamic RGB lighting with multiple color modes. The omnidirectional pickup pattern captures sound from all directions.", desc1:"With USB plug-and-play connectivity and built-in sound card, this microphone requires no additional equipment. The adjustable stand allows precise positioning.", desc2:"Perfect for gamers and streamers on a budget, this microphone delivers decent audio quality with 16-bit/48kHz sampling.", feature:"Dynamic RGB Lighting", feature1:"Omnidirectional Pickup", feature2:"Plug-and-Play USB", feature3:"Adjustable Stand", feature4:"16-bit/48kHz Sampling"},
    {productId: 28, category: "peripheral", type: "headphone", brand: "TITAN", name: "TITAN THP-307 RGB GAMING HEADSET 3.5MM", price: 509.00, image: "https://souqaalam.com/wp-content/uploads/2021/11/img_5328-03.jpg", desc:"The Titan THP-307 gaming headset features dynamic RGB lighting on the earcups for vibrant gaming aesthetics. The 40mm drivers deliver decent audio for gaming and music.", desc1:"With a flexible omnidirectional microphone that rotates 120°, this headset provides clear communication in games. The lightweight design ensures comfort.", desc2:"Compatible with PC, PS4, Xbox One, and mobile devices via 3.5mm jack. The in-line controls allow easy volume adjustment.", feature:"40mm Drivers", feature1:"RGB Lighting", feature2:"Omnidirectional Mic", feature3:"Lightweight Design", feature4:"Multi-Platform Compatibility"},
    {productId: 29, category: "peripheral", type: "headphone", brand: "RAZER", name: "RAZER BARRACUDA X (2022) BLACK", price: 4795.00, image: "https://gamextreme.ph/cdn/shop/products/1_61f1deee-454f-470e-9ed3-b690d86f034b.png?v=1654657905", desc:"The Razer Barracuda X (2022) is a versatile wireless gaming headset that works across multiple platforms including PC, PlayStation, and mobile via USB-C dongle.", desc1:"Featuring Razer TriForce 40mm drivers that deliver distinct highs, mids, and lows. The detachable HyperClear Cardioid microphone ensures crystal-clear voice capture.", desc2:"With up to 50 hours of battery life and lightweight design, this headset is perfect for extended gaming sessions. The memory foam ear cushions provide comfort.", feature:"TriForce 40mm Drivers", feature1:"50-Hour Battery Life", feature2:"Detachable Mic", feature3:"Multi-Platform Compatibility", feature4:"Memory Foam Cushions"},
    {productId: 30, category: "peripheral", type: "headphone", brand: "JBL", name: "JBL T720 BT BLUE WIRELESS OVER-EAR", price: 4699.00, image: "https://jblstore.com.ph/cdn/shop/files/Tune720BT_Blue_1.png?v=1741527434", desc:"The JBL Tune 720BT in stylish blue features Pure Bass sound that delivers powerful low frequencies. The wireless over-ear design provides comfort for extended use.", desc1:"With Bluetooth 5.3 connectivity and multi-point pairing, you can easily switch between devices. The 50-hour battery life ensures uninterrupted playback.", desc2:"The lightweight design and soft ear cushions make these headphones comfortable for all-day wear. Built-in controls allow easy music management.", feature:"Pure Bass Sound", feature1:"50-Hour Battery", feature2:"Bluetooth 5.3", feature3:"Multi-Point Pairing", feature4:"Lightweight Design"},
    {productId: 31, category: "networking", type: "ap", brand: "ASUS", name: "ASUS RT-N12+ WiFi Router", price: 1161.00, image: "https://www.asus.com/media/global/products/OyyhUJAB1nJdlmyI/pUfStNTQQtV4Rgl5_setting_xxx_0_90_end_2000.png", desc:"The ASUS RT-N12+ is an affordable 300Mbps wireless N router ideal for small homes. The two external antennas provide stable Wi-Fi coverage up to 1000 sq ft.", desc1:"Featuring four 10/100Mbps LAN ports and WPS one-touch setup. The intuitive web interface allows quick configuration.", desc2:"With multiple operation modes including router and access point, this versatile device can adapt to various networking needs.", feature:"300Mbps Wireless N", feature1:"Two External Antennas", feature2:"Four LAN Ports", feature3:"WPS One-Touch Setup", feature4:"Multiple Operation Modes"},
    {productId: 32, category: "networking", type: "ap", brand: "ASUS", name: "ASUS RP-AC52", price: 2196.00, image: "https://www.complink.com.ph/cdn/shop/products/000001_24182_500x500.jpg?v=1591982322", desc:"The ASUS RP-AC52 is a dual-band wireless range extender that boosts Wi-Fi coverage up to 2000 sq ft. The two external antennas ensure stable connections.", desc1:"With simultaneous 2.4GHz (300Mbps) and 5GHz (433Mbps) bands, this extender reduces interference. The signal indicator helps find optimal placement.", desc2:"Featuring AP, repeater, and media bridge modes for flexible deployment. The compact wall-plug design saves space.", feature:"Dual-Band 750Mbps", feature1:"Two External Antennas", feature2:"Signal Indicator", feature3:"Multiple Operation Modes", feature4:"Wall-Plug Design"},
    {productId: 33, category: "networking", type: "ap", brand: "ASUS", name: "ASUS Lyra Trio (3-Pack)", price: 15000.00, image: "https://www.complink.com.ph/cdn/shop/products/000000_23847.jpg?v=1591980067", desc:"The ASUS Lyra Trio whole-home mesh Wi-Fi system (3-pack) delivers seamless coverage up to 5,400 sq ft. Each node provides AC1300 dual-band Wi-Fi.", desc1:"With easy setup through the ASUS Router app and self-organizing network technology. The compact, wall-pluggable design eliminates bulky routers.", desc2:"Featuring advanced security with AiProtection powered by Trend Micro. The tri-band backhaul ensures stable connections between nodes.", feature:"Whole-Home Mesh", feature1:"5400 sq ft Coverage", feature2:"AC1300 Dual-Band", feature3:"AiProtection Security", feature4:"Self-Organizing Network"},
    {productId: 34, category: "networking", type: "switch", brand: "TP-LINK", name: "TP-Link TL-SF1008D", price: 560.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVH-uXASuRynVVrsu-HDxF_6_TnhXVE6-xOw&s", desc:"The TP-Link TL-SF1008D is an 8-port 10/100Mbps desktop switch that easily expands your wired network. The plug-and-play operation requires no configuration.", desc1:"With IEEE 802.3x flow control and non-blocking switching architecture. The compact and fanless design operates silently.", desc2:"LED indicators provide port status and activity monitoring. The durable metal casing helps dissipate heat.", feature:"8-Port 10/100Mbps", feature1:"Plug-and-Play", feature2:"Non-Blocking Architecture", feature3:"Fanless Silent Operation", feature4:"Metal Casing"},
    {productId: 35, category: "networking", type: "switch", brand: "TP-LINK", name: "TP-Link TL-SF1016D", price: 1390.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1Ryi0oHAt2tf4d8TuX0F8pGVRcfNVpPVfAA&s", desc:"The TP-Link TL-SF1016D is a 16-port 10/100Mbps unmanaged switch that provides simple network expansion. The plug-and-play design requires no configuration.", desc1:"Featuring non-blocking switching architecture that forwards packets at full wire speed. The IEEE 802.3x flow control ensures reliable data transfer.", desc2:"With sturdy metal casing, fanless operation, and LED indicators. The compact desktop design saves space.", feature:"16-Port 10/100Mbps", feature1:"Plug-and-Play", feature2:"Non-Blocking Switching", feature3:"Fanless Operation", feature4:"Metal Casing"},
    {productId: 36, category: "networking", type: "switch", brand: "TP-LINK", name: "TP-Link TL-SG1005D", price: 999.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8iCcp22jPe0UI6fsv7oKL5agrFNwVIsGePg&s", desc:"The TP-Link TL-SG1005D is a 5-port Gigabit desktop switch that provides high-speed wired connections up to 1000Mbps. The plug-and-play operation makes network expansion effortless.", desc1:"With non-blocking switching architecture and 10Gbps switching capacity. The energy-efficient technology reduces power consumption.", desc2:"The compact metal design operates silently and fits easily into any home or office environment. LED indicators show port status.", feature:"5-Port Gigabit", feature1:"Plug-and-Play", feature2:"10Gbps Switching Capacity", feature3:"Energy-Efficient", feature4:"Metal Casing"},
    {productId: 37, category: "networking", type: "netcard", brand: "TP-LINK", name: "TP-LINK TL-WN881ND 300MBPS Wireless", price: 750.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx3fRR6NqrJJ6qkS--3FhUU7Gcar0qguJEVw&s", desc:"The TP-Link TL-WN881ND is a PCI Express wireless network adapter that adds 300Mbps Wi-Fi connectivity to desktop PCs. The single external antenna provides stable wireless connections.", desc1:"Compatible with IEEE 802.11n standards and backward compatible with 802.11b/g devices. The advanced QoS technology prioritizes bandwidth.", desc2:"With WPS button for one-touch secure connection and WPA/WPA2 encryption. The low-profile bracket fits small form factor cases.", feature:"300Mbps Wireless N", feature1:"PCI Express Interface", feature2:"External Antenna", feature3:"WPS One-Touch Setup", feature4:"Low-Profile Bracket"},
    {productId: 38, category: "networking", type: "netcard", brand: "TP-LINK", name: "TP-LINK TL-UE300 USB 3.0 to Gigabit Ethernet Network Adapter", price: 880.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThET6hSEMEOgGpwuXLe2QXrGHltGv1lgLtXA&s", desc:"The TP-Link TL-UE300 adds Gigabit Ethernet connectivity to laptops via USB 3.0 port. The compact design is ideal for ultrabooks lacking built-in Ethernet.", desc1:"With USB 3.0 SuperSpeed interface providing up to 5Gbps bandwidth. The plug-and-play operation requires no drivers for Windows and macOS.", desc2:"The 1.5m cable provides flexible placement, while the LED indicator shows connection status. Perfect for stable wired connections.", feature:"Gigabit Ethernet", feature1:"USB 3.0 Interface", feature2:"Plug-and-Play", feature3:"1.5m Cable", feature4:"LED Indicator"},
    {productId: 39, category: "networking", type: "netcard", brand: "TP-LINK", name: "TP-LINK TG-3468 Gigabit PCI Express Network Adapter", price: 600.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTT6i-zUyJr56xitnn-OJ7LzF6ZXZx_6Ywaw&s", desc:"The TP-Link TG-3468 is a Gigabit PCI Express network adapter for desktop PCs. The low-profile design fits both standard and small form factor cases.", desc1:"Featuring advanced power management technology. The adapter supports Wake-on-LAN and PXE boot for remote management.", desc2:"With plug-and-play installation and driver support for Windows and Linux. The durable construction ensures reliable operation.", feature:"Gigabit Ethernet", feature1:"PCI Express Interface", feature2:"Low-Profile Design", feature3:"Wake-on-LAN", feature4:"Plug-and-Play"},
    {productId: 40, category: "networking", type: "router", brand: "MERCUSYS", name: "MERCUSYS MW305R 300Mbps Wireless-N Router", price: 680.00, image: "https://dynaquestpc.com/cdn/shop/files/MercusysMW305R300MbpsWirelessNRouter.jpg?v=1690438191&width=500", desc:"The Mercusys MW305R is an affordable 300Mbps wireless N router with four external antennas for enhanced coverage. The simple setup makes it ideal for home users.", desc1:"With four 10/100Mbps LAN ports and WPS one-touch connection. The IP QoS prioritizes bandwidth for smoother online activities.", desc2:"The intuitive web interface allows quick configuration. The compact white design with vertical placement saves space.", feature:"300Mbps Wireless N", feature1:"Four External Antennas", feature2:"Four LAN Ports", feature3:"WPS One-Touch", feature4:"Vertical Design"},
    {productId: 41, category: "networking", type: "router", brand: "MERCUSYS", name: "MERCUSYS MR90X AX6000 8-Stream Wi-Fi 6 Router", price: 7990.00, image: "https://static.mercusys.com/product-image/1_large20221108011748.jpg", desc:"The Mercusys MR90X is a high-performance Wi-Fi 6 router delivering AX6000 dual-band speeds. The eight high-gain antennas provide whole-home coverage.", desc1:"Featuring OFDMA and MU-MIMO technology that supports multiple devices. The 2.5G WAN port enables ultra-fast internet connections.", desc2:"With easy setup via mobile app and advanced security features. The sleek tower design promotes better heat dissipation.", feature:"Wi-Fi 6 AX6000", feature1:"Eight High-Gain Antennas", feature2:"2.5G WAN Port", feature3:"OFDMA & MU-MIMO", feature4:"Mobile App Management"},
    {productId: 42, category: "networking", type: "router", brand: "D-LINK", name: "D-Link R15 AX1500 Smart Router", price: 1850.00, image: "https://www.dlink.co.id/wp-content/uploads/2021/09/Front.jpg", desc:"The D-Link R15 is an AX1500 Wi-Fi 6 router that delivers faster speeds and better efficiency. The dual-band supports more connected devices.", desc1:"With OFDMA technology that reduces latency. The four external antennas provide reliable coverage.", desc2:"Featuring WPA3 security, parental controls, and QoS prioritization. The compact design fits easily into any home.", feature:"Wi-Fi 6 AX1500", feature1:"Dual-Band", feature2:"OFDMA Technology", feature3:"Four External Antennas", feature4:"WPA3 Security"},
    {productId: 43, category: "networking", type: "router", brand: "TP-LINK", name: "TP-LINK TL-WR840N 300Mbps Wireless N Speed Router", price: 700.00, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFyRHLNONlCb3p_llBJMW4kuuhJUa_xKSa2g&s", desc:"The TP-Link TL-WR840N is a basic 300Mbps wireless N router with two external antennas. The simple setup makes it ideal for small homes.", desc1:"With four 10/100Mbps LAN ports for wired connections. The IP-based bandwidth control helps manage network traffic.", desc2:"The intuitive web interface allows easy configuration. The compact design saves space.", feature:"300Mbps Wireless N", feature1:"Two External Antennas", feature2:"Four LAN Ports", feature3:"Bandwidth Control", feature4:"Compact Design"},
    {productId: 44, category: "networking", type: "switch", brand: "ZYXEL", name: "ZYXEL GS1915-8EP 8-port GbE Smart Managed Switch", price: 9200.00, image: "https://store.zyxel.com/media/catalog/category/img_xmg1915-18ep_p_1000x1000_1.jpg", desc:"The Zyxel GS1915-8EP is an 8-port Gigabit smart managed switch with 4 PoE+ ports. The web-managed interface offers advanced features.", desc1:"Featuring VLAN, QoS, port mirroring, and link aggregation. The fanless design ensures silent operation.", desc2:"With energy-efficient Ethernet and comprehensive security features. The sturdy metal housing provides durability.", feature:"8-Port Gigabit", feature1:"4 PoE+ Ports", feature2:"Web-Managed", feature3:"Fanless Design", feature4:"Metal Housing"},
    {productId: 45, category: "networking", type: "switch", brand: "UBIQUITI", name: "UBIQUITI USW-Ultra-60W Switch", price: 9250.00, image: "https://www.netxl.com/_next/image/?url=https%3A%2F%2Fstorage.googleapis.com%2Fnxl-content%2Fubiquiti%2Fusw-ultra-60w-11.jpg&w=2560&q=75", desc:"The Ubiquiti USW-Ultra-60W is a compact 8-port Gigabit managed switch with 60W PoE budget. The fanless design ensures silent operation.", desc1:"With Layer 2 management features accessible through UniFi Network Controller. The 10G SFP+ uplink port enables high-speed connectivity.", desc2:"Featuring advanced security protocols and energy-efficient technology. The sleek metal housing matches Ubiquiti's aesthetic.", feature:"8-Port Gigabit", feature1:"60W PoE Budget", feature2:"10G SFP+ Uplink", feature3:"UniFi Managed", feature4:"Fanless Design"},
    {productId: 46, category: "gaming", type: "controller", brand: "GAMESIR", name: "GameSir Tarantula Pro Multi-Platform Wireless Symmetric Pro Controller", price: 2695.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/tarantula-pro1-ECOM-MAIN-IMAGE-1_700x.jpg?v=1727060994", desc:"The GameSir Tarantula Pro is a versatile wireless controller compatible with PC, Android, and Nintendo Switch. The symmetrical stick layout and textured grips provide comfortable gaming.", desc1:"Featuring Hall Effect joysticks and triggers that eliminate drift. The built-in 800mAh battery offers up to 25 hours of playtime.", desc2:"With 2.4GHz wireless and Bluetooth 5.0 connectivity options. The RGB lighting adds customizable flair.", feature:"Multi-Platform Compatibility", feature1:"Hall Effect Joysticks", feature2:"25-Hour Battery", feature3:"RGB Lighting", feature4:"Programmable Buttons"},
    {productId: 47, category: "gaming", type: "console", brand: "MSI", name: "MSI Gaming Claw 8", price: 57995.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/2_da4bb76d-6d60-40b5-9775-858c0ba721e3_700x.jpg?v=1739925123", desc:"The MSI Gaming Claw 8 is a powerful handheld gaming PC featuring an Intel Core Ultra processor. The 8-inch 120Hz Full HD touchscreen delivers smooth gameplay.", desc1:"With Windows 11 operating system, this device provides access to PC game libraries. The Hall Effect triggers and joysticks ensure precise control.", desc2:"Featuring a 53Whr battery for extended play sessions. The ergonomic design with RGB lighting combines comfort and style.", feature:"Intel Core Ultra", feature1:"8-inch 120Hz Display", feature2:"Hall Effect Controls", feature3:"Windows 11", feature4:"53Whr Battery"},
    {productId: 48, category: "gaming", type: "controller", brand: "MSI", name: "MSI Force Pro Wireless Stalker 2", price: 6795.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/xchmxfghm_700x.jpg?v=1736766235", desc:"The MSI Force Pro Wireless is an official Stalker 2 licensed controller featuring immersive haptic feedback. The premium build includes metal components.", desc1:"With 2.4GHz wireless and Bluetooth connectivity. The Hall Effect sensors prevent drift.", desc2:"The ergonomic design with textured grips ensures comfort. Customizable RGB lighting allows personalization.", feature:"Haptic Feedback", feature1:"Hall Effect Sensors", feature2:"Multi-Platform", feature3:"RGB Lighting", feature4:"Premium Build"},
    {productId: 49, category: "gaming", type: "controller", brand: "REDDRAGON", name: "Redragon Saturn Wired Gamepad (G807)", price: 700.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/products/61nKgRfmFmL._AC_SL1500_700x.jpg?v=1736412111", desc:"The Redragon Saturn G807 is an affordable wired controller for PC with dual vibration feedback. The precise analog sticks provide responsive gameplay.", desc1:"Featuring programmable turbo function. The 2m braided cable ensures durability.", desc2:"With plug-and-play USB connectivity. The non-slip grips ensure comfortable control.", feature:"Dual Vibration", feature1:"Programmable Turbo", feature2:"Braided Cable", feature3:"Non-Slip Grips", feature4:"Plug-and-Play"},
    {productId: 50, category: "gaming", type: "controller", brand: "REDDRAGON", name: "Redragon Jupiter Bluetooth Gamepad (G809)", price: 2295.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/products/1_1_e35db5dd-674b-46b0-9e12-d4ac26fa8a7c_700x.jpg?v=1676786249", desc:"The Redragon Jupiter G809 is a wireless Bluetooth controller compatible with PC and mobile. The ergonomic design provides comfort during extended play.", desc1:"Featuring motion controls and dual vibration feedback. The built-in 600mAh battery offers up to 10 hours.", desc2:"With programmable turbo function and 3.5mm headphone jack. The RGB lighting makes this an affordable alternative.", feature:"Bluetooth Wireless", feature1:"Motion Controls", feature2:"10-Hour Battery", feature3:"RGB Lighting", feature4:"Programmable Turbo"},
    {productId: 51, category: "gaming", type: "console", brand: "SONY", name: "Sony Playstation PS5 Console Digital Version 30th Anniversary Edition (CFI-2000 B30)", price: 39990.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/cvbncvhm_700x.jpg?v=1736225051", desc:"The PlayStation 5 Digital Edition 30th Anniversary model celebrates PlayStation's legacy with unique colors. This all-digital console plays PS5 games without discs.", desc1:"Featuring ultra-high speed SSD and 4K UHD output. The DualSense wireless controller offers immersive haptic feedback.", desc2:"With 825GB SSD storage and compatibility with PlayStation VR2. This limited edition includes special startup sounds.", feature:"30th Anniversary Design", feature1:"825GB SSD", feature2:"4K UHD Output", feature3:"DualSense Controller", feature4:"PS VR2 Compatible"},
    {productId: 52, category: "gaming", type: "console", brand: "NINTENDO", name: "Nintendo Switch Console", price: 14750.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/Nintendo-Switch-OLED-Console-White-Joy-Con_a3608daf-6126-4f00-830e-c0face6d5d39_700x.jpg?v=1736312410", desc:"The Nintendo Switch OLED model features a vibrant 7-inch OLED screen. The versatile design transitions between TV, tabletop, and handheld modes.", desc1:"With 64GB internal storage and improved audio. The wide adjustable stand offers better stability.", desc2:"Includes all the features of the original Switch with enhanced dock. The white Joy-Con present a sleek aesthetic.", feature:"7-inch OLED", feature1:"64GB Storage", feature2:"Enhanced Audio", feature3:"Adjustable Stand", feature4:"White Design"},
    {productId: 53, category: "gaming", type: "console", brand: "XBOX", name: "Xbox Series X", price: 25762.55, image: "https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/b00-XSX-Teaser-Dec-2019", desc:"The Xbox Series X is Microsoft's most powerful console, featuring 12 teraflops of processing power. The custom SSD virtually eliminates load times.", desc1:"With backward compatibility for thousands of games. The Quick Resume feature lets you switch between multiple games instantly.", desc2:"Includes the Xbox Wireless Controller with textured grip. The tower design delivers performance without compromise.", feature:"12 Teraflops", feature1:"Custom SSD", feature2:"Backward Compatibility", feature3:"Quick Resume", feature4:"Xbox Wireless Controller"},
    {productId: 54, category: "gaming", type: "controller", brand: "XBOX", name: "XBOX Elite Series 2 Core Wireless Controller (Asian)", price: 7995.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/61rnJLa6OfL._SL1500_21875bc7-65cb-439d-91c8-39578828f291_700x.jpg?v=1696131565", desc:"The Xbox Elite Wireless Controller Series 2 Core offers customizable gaming with adjustable-tension thumbsticks. The white design presents a clean aesthetic.", desc1:"Featuring up to 40 hours of rechargeable battery life. The included USB-C cable enables wired play.", desc2:"With interchangeable components and button mapping. This pro-level controller provides competitive advantage.", feature:"Adjustable-Tension Thumbsticks", feature1:"40-Hour Battery", feature2:"Interchangeable Components", feature3:"Button Mapping", feature4:"White Design"},
    {productId: 55, category: "gaming", type: "console", brand: "XBOX", name: "XBOX Series S 1TB SSD All-Digital Console", price: 19450.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/ff0f7631-df48-4ff6-868a-45cd0dd47edd_700x.jpg?v=1695441875", desc:"The Xbox Series S 1TB model delivers next-gen performance in a compact design. Experience faster load times and up to 120fps gameplay at 1440p.", desc1:"With Xbox Velocity Architecture for quick resume. The carbon black color scheme distinguishes this model.", desc2:"Includes the Xbox Wireless Controller. The small form factor makes it ideal for limited space.", feature:"1TB SSD", feature1:"1440p 120fps", feature2:"Quick Resume", feature3:"Carbon Black", feature4:"Xbox Wireless Controller"},
    {productId: 56, category: "gaming", type: "controller", brand: "REDDRAGON", name: "Redragon G817 Hoarah Mobile Game Controller", price: 1495.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/bbfddfbbfddf_700x.jpg?v=1740120100", desc:"The Redragon G817 Hoarah is a mobile gaming controller with telescopic design. The ergonomic grip provides console-like gaming on Android devices.", desc1:"Featuring Bluetooth 5.0 connectivity with low latency. The adjustable phone clamp securely holds devices.", desc2:"With dual vibration motors and programmable turbo function. The compact folding design makes it easy to carry.", feature:"Telescopic Design", feature1:"Bluetooth 5.0", feature2:"Adjustable Clamp", feature3:"Dual Vibration", feature4:"Programmable Turbo"},
    {productId: 57, category: "gaming", type: "controller", brand: "NINTENDO", name: "WII ARCADE FIGHTER", price: 1395.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/products/81dYzGN3YKL._SL1500_700x.png?v=1676904260", desc:"The Wii Arcade Fighter is a classic-style fight stick controller for Nintendo Wii. The large joystick and responsive buttons recreate authentic arcade gameplay.", desc1:"With plug-and-play USB connectivity. The non-slip base keeps the controller stable.", desc2:"Perfect for classic fighting games. The compact size fits easily in entertainment centers.", feature:"Arcade Stick", feature1:"USB Connectivity", feature2:"Non-Slip Base", feature3:"Responsive Buttons", feature4:"Compact Design"},
    {productId: 58, category: "gaming", type: "controller", brand: "HORI", name: "Hori Real Arcade Pro. V Hayabusa For Windows PC (HPC-064)", price: 5495.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/6975977473086_700x.jpg?v=1723780760", desc:"The Hori Real Arcade Pro. V Hayabusa features premium arcade components. The full-size design provides comfortable play for fighting game enthusiasts.", desc1:"With USB connectivity for PC. The anti-slip mat ensures stability.", desc2:"The tournament-grade components offer precise inputs. The sleek design matches Hori's premium lineup.", feature:"Hayabusa Components", feature1:"Full-Size Design", feature2:"USB Connectivity", feature3:"Anti-Slip Mat", feature4:"Tournament-Grade"},
    {productId: 59, category: "gaming", type: "controller", brand: "HORI", name: "Hori PS5 Fighting Stick Mini for PS5/ PS4/ PC (SPF-038A)", price: 2695.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/Untitled-1-Recovered_2fd9fb82-1bc7-44c5-b69e-399854a4bca3_700x.jpg?v=1706233792", desc:"The Hori Fighting Stick Mini is a compact arcade controller for PS5, PS4, and PC. The smaller form factor makes it ideal for casual players.", desc1:"Featuring authentic arcade-style joystick and buttons. The USB plug-and-play works without drivers.", desc2:"With lock switch to disable specific buttons. The affordable price provides entry-level experience.", feature:"Compact Design", feature1:"Arcade-Style Controls", feature2:"Plug-and-Play", feature3:"Button Lock", feature4:"Affordable"},
    {productId: 60, category: "gaming", type: "controller", brand: "HORI", name: "Hori Tekken 8 PS5 Fighting Stick A for PS5/ PS4/ PC (SPF-037A)", price: 12950.00, image: "https://ecommerce.datablitz.com.ph/cdn/shop/files/bdffddffd_700x.jpg?v=1706235567", desc:"The Hori Tekken 8 Fighting Stick A is an officially licensed arcade controller. The full-size design includes premium Hayabusa components.", desc1:"With touchpad functionality for PS5 compatibility. The anti-slip base provides stability.", desc2:"The tournament-grade components ensure precise inputs. The striking design makes this a must-have.", feature:"Tekken 8 Licensed", feature1:"Hayabusa Components", feature2:"Touchpad Functionality", feature3:"Anti-Slip Base", feature4:"Tournament-Grade"},
    {productId: 61, category: "peripheral", type: "mouse", brand: "CORSAIR", name: "SCIMITAR RGB ELITE Optical MOBA/MMO Gaming Mouse", price: 4536.43, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Mice/CH-9304211-NA/Gallery/Scimitar_ELITE_BLK_01.webp", desc:"The Corsair Scimitar RGB Elite is an MMO-optimized mouse featuring a unique 12-button mechanical keypad. The ultra-accurate 18,000 DPI optical sensor delivers precision.", desc1:"With Omron switches rated for 50-million clicks. The customizable RGB lighting syncs with Corsair iCUE.", desc2:"The contoured shape with textured side grips provides comfort. The onboard storage saves up to three profiles.", feature:"12-Button Keypad", feature1:"18,000 DPI", feature2:"Omron Switches", feature3:"Chroma RGB", feature4:"Onboard Profiles"},
    {productId: 62, category: "peripheral", type: "mouse", brand: "CORSAIR", name: "HARPOON RGB WIRELESS Gaming Mouse", price: 3402.18, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Mice/CH-9311011-NA/Gallery/Harpoon_RGB_Wireless_01.webp", desc:"The Corsair Harpoon RGB Wireless combines 2.4GHz SLIPSTREAM wireless and Bluetooth connectivity. The lightweight design is ideal for FPS gaming.", desc1:"Featuring a 10,000 DPI optical sensor. The contoured shape with rubber side grips ensures comfort.", desc2:"With up to 60 hours of battery life. The included USB receiver stores neatly in the mouse.", feature:"SLIPSTREAM Wireless", feature1:"10,000 DPI", feature2:"60-Hour Battery", feature3:"Rubber Grips", feature4:"Lightweight"},
    {productId: 63, category: "peripheral", type: "mouse", brand: "CORSAIR", name: "HARPOON RGB PRO FPS/MOBA Gaming Mouse", price: 1984.37, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Mice/CH-9301111-NA/Gallery/Harpoon_RGB_PRO_01.webp", desc:"The Corsair Harpoon RGB PRO is a wired gaming mouse optimized for FPS titles. The lightweight design provides comfortable, precise control.", desc1:"With a 12,400 DPI optical sensor. The six programmable buttons allow personalized configurations.", desc2:"The dynamic RGB lighting syncs with Corsair devices. The braided fiber cable ensures durability.", feature:"12,400 DPI", feature1:"Six Programmable Buttons", feature2:"RGB Lighting", feature3:"Braided Cable", feature4:"Lightweight"},
    {productId: 64, category: "peripheral", type: "mouse", brand: "CORSAIR", name: "M75 WIRELESS Lightweight RGB Gaming Mouse", price: 7372.06, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Mice/base-m75-wireless-apple-config/gallery/glacial-blue/M75_GLACIAL_BLUE_01.webp", desc:"The Corsair M75 Wireless is an ultra-lightweight gaming mouse featuring QUICKSTRIKE buttons. The MARKSMAN 26K DPI optical sensor delivers precision.", desc1:"With 2.4GHz SLIPSTREAM wireless and Bluetooth 5.2. The symmetrical shape ensures smooth control.", desc2:"Featuring up to 100 hours of battery life. The premium build includes aluminum scroll wheel.", feature:"26K DPI", feature1:"QUICKSTRIKE Buttons", feature2:"100-Hour Battery", feature3:"Aluminum Scroll", feature4:"Lightweight"},
    {productId: 65, category: "peripheral", type: "keyboard", brand: "CORSAIR", name: "K70 RGB TKL CHAMPION SERIES Optical-Mechanical Gaming Keyboard with PBT DOUBLE SHOT PRO Keycaps (NA)", price: 7372.06, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Keyboards/CH-911901A-NA/Gallery/CH-911901A-NA_01.webp", desc:"The Corsair K70 RGB TKL Champion Series features CORSAIR OPX optical-mechanical switches. The tournament-approved tenkeyless design saves desk space.", desc1:"With durable PBT double-shot PRO keycaps. The aircraft-grade aluminum frame ensures stability.", desc2:"The detachable USB Type-C cable and onboard storage make this ideal for competitive gamers. The included wrist rest provides comfort.", feature:"OPX Optical Switches", feature1:"PBT Keycaps", feature2:"Tenkeyless", feature3:"Aluminum Frame", feature4:"Onboard Storage"},
    {productId: 66, category: "peripheral", type: "keyboard", brand: "CORSAIR", name: "K70 PRO MINI WIRELESS 60% Mechanical CHERRY MX Speed Switch Keyboard with RGB Backlighting", price: 10207.68, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Keyboards/CH-9189014-NA/Gallery/K70_PRO_MINI_WIRELESS_PBT_01.webp", desc:"The Corsair K70 PRO Mini Wireless is a 60% form factor keyboard featuring CHERRY MX Speed Silver switches. The triple-mode connectivity includes SLIPSTREAM wireless.", desc1:"With PBT double-shot keycaps and 8,000Hz hyper-polling. The vibrant per-key RGB lighting syncs across devices.", desc2:"The compact design saves space while maintaining functionality. The included tools allow customization.", feature:"CHERRY MX Speed", feature1:"60% Compact", feature2:"Triple-Mode", feature3:"8000Hz Polling", feature4:"PBT Keycaps"},
    {productId: 67, category: "peripheral", type: "keyboard", brand: "CORSAIR", name: "K57 RGB WIRELESS Gaming Keyboard", price: 6237.81, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Keyboards/CH-925C015-NA/Gallery/K57_RGB_WIRELESS_NA_01.webp", desc:"The Corsair K57 RGB Wireless features low-profile keys with quiet, responsive typing experience perfect for both gaming and office work. Utilizing SLIPSTREAM wireless technology with sub-1ms latency, this keyboard delivers lag-free performance comparable to wired models, while the dynamic per-key RGB backlighting offers extensive customization through Corsair's iCUE software. The included soft-touch palm rest enhances comfort during extended sessions, making it ideal for gamers who also need to type frequently.", desc1:"With dedicated media controls and USB passthrough port, the K57 provides convenient access to volume adjustment and peripheral connectivity. The slim profile design saves desk space while maintaining full-size functionality, and the quiet key switches won't disturb others in shared spaces. The 2.4GHz wireless connection offers reliable performance up to 10m away, with the USB receiver storing neatly in the keyboard's underside for travel. A built-in rechargeable battery provides up to 40 hours of use with lighting enabled.", desc2:"This versatile keyboard bridges the gap between gaming and productivity, featuring anti-ghosting with full-key rollover for competitive play. The durable construction withstands heavy daily use, while the spill-resistant design protects against accidental liquid damage. Whether you're gaming, working, or streaming, the K57 RGB Wireless delivers premium features in an accessible package that complements any setup.", feature:"SLIPSTREAM Wireless: Sub-1ms latency comparable to wired keyboards.", feature1:"Low-Profile Keys: Quiet, responsive switches with 1.4mm actuation.", feature2:"Per-Key RGB: Dynamic lighting with 16.8 million color options.", feature3:"USB Passthrough: Convenient port for mice or headsets.", feature4:"40-Hour Battery: Rechargeable with lighting enabled (175 hours without)."},
    {productId: 68, category: "peripheral", type: "keyboard", brand: "CORSAIR", name: "K70 CORE SE RGB Mechanical Gaming Keyboard – Cherry Blossom", price: 6237.81, image: "https://assets.corsair.com/image/upload/c_pad,q_85,h_1100,w_1100,f_auto/products/Gaming-Keyboards/k70-core/Gallery/CH-9109C1E/K70_CORE_CHERRY_BLOSSOM_01.webp", desc:"The Corsair K70 CORE SE in Cherry Blossom features vibrant pink and white keycaps with Japanese sub-legends, creating a stunning aesthetic inspired by sakura season. The CHERRY MX Red switches provide smooth, linear keystrokes ideal for both gaming and typing, with gold contacts ensuring durability over 100 million keystrokes. This special edition keyboard combines Corsair's renowned build quality with unique cultural styling, making it a centerpiece for any gaming setup.", desc1:"With per-key RGB backlighting that highlights the beautiful keycap design, the K70 CORE SE offers extensive customization through Corsair's iCUE software. The aircraft-grade aluminum frame ensures long-term durability while resisting flex during intense gaming sessions. The detachable soft-touch wrist rest enhances comfort during extended use, and the USB passthrough port provides convenient connectivity for mice or headsets. The media controls include a premium volume roller for quick audio adjustments without interrupting gameplay.", desc2:"This keyboard isn't just about looks – it delivers tournament-ready performance with 100% anti-ghosting and full-key rollover. The dedicated tournament switch instantly disables Windows keys and macros to prevent accidental interruptions during competitive play. The Cherry Blossom edition comes with exclusive keycap puller and switch puller tools featuring matching sakura designs, allowing enthusiasts to customize their setup further. Whether you're a fan of Japanese aesthetics or simply want a premium keyboard that stands out, the K70 CORE SE delivers both form and function.", feature:"CHERRY MX Red Switches: Linear action with 45g actuation force for smooth keystrokes.", feature1:"Japanese Sub-Legend Keycaps: PBT double-shot construction with sakura-themed designs.", feature2:"Per-Key RGB Backlighting: 16.8 million colors with dynamic lighting effects.", feature3:"Aircraft-Grade Aluminum Frame: Rugged construction that resists warping and flex.", feature4:"iCUE Software Integration: Syncs lighting with other Corsair peripherals and components."}
];

// Prepare data list
const searchData = product.map(item => item.name);

// Desktop elements
const desktopInput = document.getElementById("searchInput");
const desktopResults = document.getElementById("searchResults");

// Mobile elements
const mobileInput = document.getElementById("mobileSearchInput");
const mobileResults = document.getElementById("mobileSearchResults");

// Utility function to handle input events
function handleSearch(inputEl, resultsEl) {
    const query = inputEl.value.toLowerCase().trim();

    if (query.length === 0) {
        resultsEl.style.display = "none";
        resultsEl.innerHTML = "";
        return;
    }

    const matched = product.filter(item => 
        item.name.toLowerCase().includes(query)
    );

    if (matched.length > 0) {
        resultsEl.innerHTML = matched.map(item => `
            <p class="search-result" data-product-id="${item.productId}">${item.name}</p>
        `).join("");
        resultsEl.style.display = "block";
        
        // Add click handler to each result
        resultsEl.querySelectorAll('.search-result').forEach(el => {
            el.addEventListener('click', () => {
                const productId = el.dataset.productId;
                sessionStorage.setItem("selectedProduct", productId);
                window.location.href = "../html/product.html";
            });
        });
    } else {
        resultsEl.innerHTML = "<p>No results found</p>";
        resultsEl.style.display = "block";
    }
}

// Redirect function that uses the product ID



// Attach event listeners for desktop
if (desktopInput && desktopResults) {
    desktopInput.addEventListener("input", () => handleSearch(desktopInput, desktopResults));
}

// Attach event listeners for mobile
if (mobileInput && mobileResults) {
    mobileInput.addEventListener("input", () => handleSearch(mobileInput, mobileResults));
}

// Hide dropdowns when clicking outside
document.addEventListener("click", (e) => {
    if (!e.target.closest(".search-box")) {
        if (desktopResults) desktopResults.style.display = "none";
    }
    if (!e.target.closest(".mobile-search-container")) {
        if (mobileResults) mobileResults.style.display = "none";
    }
});

// === Search Box Input === //

// === Close button for mobile search === //
const mobileSearchClear = document.getElementById('mobileSearchClear');

// Show/hide the X based on input content
mobileInput.addEventListener('input', () => {
if (mobileInput.value.trim() !== '') {
    mobileSearchClear.style.display = 'block';
} else {
    mobileSearchClear.style.display = 'none';
    mobileResults.style.display = 'none';
    mobileResults.innerHTML = '';
}
});

// Clear input and hide results when X is clicked
if (mobileSearchClear) {
mobileSearchClear.addEventListener('click', () => {
    mobileInput.value = '';
    mobileResults.style.display = 'none';
    mobileResults.innerHTML = '';
    mobileSearchClear.style.display = 'none';
    mobileInput.focus();
});
}

// == Responsive mobile search box == //
const searchToggle = document.querySelector('.search-toggle');
const mobileSearch = document.querySelector('.mobile-search-container');

searchToggle.addEventListener('click', () => {
const isHidden = window.getComputedStyle(mobileSearch).display === 'none';

if (isHidden) {
    mobileSearch.style.display = 'flex';
} else {
    mobileSearch.style.display = 'none';
}
});

function handleResize() {
    if (window.innerWidth > 768) {
        // Desktop view: hide mobile search and clear mobile input & results
        mobileSearch.style.display = 'none';
        if (mobileInput) {
            mobileInput.value = '';
        }
        if (mobileResults) {
            mobileResults.style.display = 'none';
            mobileResults.innerHTML = '';
        }
    } else {
        // Mobile view: hide desktop results and clear desktop input & results
        if (desktopResults) {
            desktopResults.style.display = 'none';
            desktopResults.innerHTML = '';
        }
        if (desktopInput) {
            desktopInput.value = '';
        }
        // Hide mobile search container initially
        mobileSearch.style.display = 'none';
    }


    if (window.innerWidth <= 768) {
        if (mobileInput.value.trim() !== '') {
        mobileSearchClear.style.display = 'block';
        } else {
        mobileSearchClear.style.display = 'none';
        }
    } else {
        mobileSearchClear.style.display = 'none'; // Always hide on desktop
    }
}

handleResize();

window.addEventListener('resize', handleResize);
